name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    - name: Restore Dependencies
      run: dotnet restore
    
    - name: Build Windows Executable
      run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish
      
    - name: Archive Published Executable
      run: Compress-Archive -Path ./publish/* -DestinationPath ./pirvarsler.zip

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: Pirvarsler
        path: ./pirvarsler.zip