name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    # Restore dependencies
    - name: Restore Dependencies
      run: dotnet restore

    # Archive the Windows Executable
    - name: Archive Published Executable
      run: Compress-Archive -Path ./publish/* -DestinationPath ./pirvarsler.zip

    # Upload the Artifact
    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: windows-console-app
        path: ./pirvarsler.zip